{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "basePath": "/api/v1",
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000/api/v1"
        }
      }
    }
  ],
  "components": {
    "securitySchemes": {
      "jwt": {
        "type": "apiKey",
        "description": "Bearer ey....",
        "name": "Authorization",
        "in": "header"
      }
    },
    "schemas": {
      "error_object": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "description": "Message"
          }
        }
      },
      "errors_object": {
        "type": "object",
        "properties": {
          "errors": {
            "$ref": "#/components/schemas/errors_map"
          }
        }
      },
      "errors_map": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "login": {
        "type": "object",
        "properties": {
          "session": {
            "$ref": "#/components/schemas/user_field"
          }
        },
        "required": [
          "session"
        ]
      },
      "new_user": {
        "type": "object",
        "properties": {
          "user": {
            "$ref": "#/components/schemas/user_field"
          }
        },
        "required": [
          "user"
        ]
      },
      "user_field": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Email",
            "example": "myemail@example.com"
          },
          "password": {
            "type": "string",
            "description": "Password",
            "example": "Password1234"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "ID"
          },
          "email": {
            "type": "string",
            "description": "Email",
            "example": "myemail@example.com"
          },
          "created_at": {
            "type": "string",
            "format": "date"
          },
          "updated_at": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "new_job": {
        "type": "object",
        "properties": {
          "job": {
            "$ref": "#/components/schemas/job_field"
          }
        },
        "required": [
          "job"
        ]
      },
      "job_field": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Job title"
          },
          "rate": {
            "type": "number",
            "description": "Salary per hour"
          },
          "language_list": {
            "type": "string",
            "description": "Spoken languages by comma separated"
          },
          "shifts_attributes": {
            "type": "array",
            "items": {
              "properties": {
                "start_time": {
                  "type": "string",
                  "format": "date-time"
                },
                "end_time": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          }
        },
        "required": [
          "title",
          "rate",
          "language_list",
          "shifts_attributes"
        ]
      },
      "job": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string",
            "description": "Job title and searchable"
          },
          "rate": {
            "type": "number",
            "description": "Salary per hour"
          },
          "languages": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Spoken languages & searchable"
          },
          "paying": {
            "type": "number",
            "description": "Salary per hour * Total shifts hours"
          },
          "shifts": {
            "type": "array",
            "items": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "start_time": {
                  "type": "string",
                  "format": "date-time"
                },
                "end_time": {
                  "type": "string",
                  "format": "date-time"
                },
                "working_hours": {
                  "type": "number"
                }
              }
            }
          }
        }
      },
      "new_job_application": {
        "type": "object",
        "properties": {
          "job_application": {
            "type": "object",
            "properties": {
              "job_id": {
                "type": "integer",
                "description": "Job Id"
              }
            }
          },
          "required": [
            "job_id"
          ]
        },
        "required": [
          "job_application"
        ]
      }
    }
  },
  "paths": {
    "/job_applications/": {
      "post": {
        "summary": "Create a job application",
        "tags": [
          "Job Applications API"
        ],
        "security": [
          {
            "jwt": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Created a job application",
            "content": {
            }
          },
          "422": {
            "description": "Validation failed if alredy applied",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/new_job_application"
              }
            }
          }
        }
      }
    },
    "/jobs/": {
      "post": {
        "summary": "Create a job with shifts",
        "tags": [
          "Jobs API"
        ],
        "security": [
          {
            "jwt": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Created a job",
            "content": {
            }
          },
          "422": {
            "description": "Validation failed for request",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/new_job"
              }
            }
          }
        }
      },
      "get": {
        "summary": "List of jobs with filters",
        "tags": [
          "Jobs API"
        ],
        "security": [
          {
            "jwt": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "title",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "language",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the filtered jobs when passing search query",
            "content": {
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Authenticate User",
        "tags": [
          "Authentication API"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "authenticates and returns a new token",
            "content": {
            }
          },
          "400": {
            "description": "returns bad when password incorrect",
            "content": {
            }
          },
          "422": {
            "description": "returns validation when incorrect params",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login"
              }
            }
          }
        }
      }
    },
    "/users/": {
      "post": {
        "summary": "Create a user",
        "tags": [
          "Users API"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Created a user",
            "content": {
            }
          },
          "422": {
            "description": "Validation failed for request",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/new_user"
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "patch": {
        "summary": "Update a user",
        "tags": [
          "Users API"
        ],
        "security": [
          {
            "jwt": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated a user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "$ref": "#/components/schemas/user"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation failed for request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "$ref": "#/components/schemas/errors_object"
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/new_user"
              }
            }
          }
        }
      }
    }
  }
}